# MarkGo Engine - Markdown Linting Configuration
# Ensures consistent documentation formatting

# Default rules
default: true

# Line length - adjust for readability
MD013:
  line_length: 120
  headings: false
  tables: false
  code_blocks: false

# Trailing spaces - allow two spaces for line breaks
MD009:
  br_spaces: 2

# Hard tabs - disabled (allow tabs in code blocks)
MD010: false

# First line in file should be a top level heading
MD041: false

# Proper names should have the correct capitalization
MD044:
  names:
    - MarkGo
    - GitHub
    - JSON
    - YAML
    - TOML
    - HTTP
    - HTTPS
    - API
    - CLI
    - RSS
    - SEO
    - CSS
    - JavaScript
    - Docker
    - Go
    - Markdown

# Emphasis used instead of a heading
MD036: false

# Fenced code blocks should be surrounded by blank lines
MD031: false

# Lists should be surrounded by blank lines
MD032: false

# Inline HTML
MD033:
  allowed_elements:
    - img
    - br
    - details
    - summary
    - sup
    - sub